# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration', '0004_user_default_gym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_gym',
        ),
    ]
