# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration', '0008_auto_20190627_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='gym_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
