# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration', '0003_auto_20190626_1312'),
        ('finder_app', '0002_preference_default_gym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='gymDay',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='gymHour',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='timePref',
        ),
        migrations.AddField(
            model_name='preference',
            name='cardio',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='endurance',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='flexibility',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='genFit',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='muscle',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='strength',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='userPref',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='login_and_registration.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='weightLoss',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='friHour',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='monHour',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='satHour',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='sunHour',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='thuHour',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='tuesHour',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='userSchedule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gymSchedule', to='login_and_registration.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='wedHour',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
