# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder_app', '0003_auto_20190626_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='cardio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preference',
            name='endurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preference',
            name='flexibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preference',
            name='genFit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preference',
            name='muscle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preference',
            name='strength',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preference',
            name='weightLoss',
            field=models.BooleanField(default=False),
        ),
    ]
