# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder_app', '0004_auto_20190626_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='cardio',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='preference',
            name='endurance',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='preference',
            name='flexibility',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='preference',
            name='genFit',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='preference',
            name='muscle',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='preference',
            name='strength',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='preference',
            name='weightLoss',
            field=models.NullBooleanField(),
        ),
    ]
