# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder_app', '0006_auto_20190626_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='friHour',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='monHour',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='satHour',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='sunHour',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='thuHour',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='tuesHour',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='wedHour',
        ),
        migrations.AddField(
            model_name='preference',
            name='user_schedule',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
