# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder_app', '0007_auto_20190626_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='userSchedule',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
