# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder_app', '0008_auto_20190627_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='default_gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='def_gym', to='login_and_registration.User'),
        ),
    ]
